apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secret.root_username | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secret.root_password | quote }}
  MONGO_USERNAME: {{ .Values.secret.username | quote }}
  MONGO_PASSWORD: {{ .Values.secret.password | quote }}
  MONGO_USERS_LIST: {{ .Values.secret.users_list | quote }}
